export const BASE_URL = "https://covid-bod.herokuapp.com";
export const LOCAL = "http://localhost:5000";

export const FETCH_CLASSES_START = "FETCH_CLASSES_START";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";
export const SEARCH_CLASSES = "SEARCH_CLASSES";
export const SEARCH_CLASSES_TIME = "SEARCH_CLASSES_TIME";

export const FETCH_INSTRUCTOR_CLASSES_START = "FETCH_INSTRUCTOR_CLASSES_START";
export const FETCH_INSTRUCTOR_CLASSES_SUCCESS =
  "FETCH_INSTRUCTOR_CLASSES_SUCCESS";
export const FETCH_INSTRUCTOR_CLASSES_FAILURE =
  "FETCH_INSTRUCTOR_CLASSES_FAILURE";

const types = {
  FETCH_CLASSES_START,
  FETCH_CLASSES_SUCCESS,
  FETCH_CLASSES_FAILURE,
  SEARCH_CLASSES,
  SEARCH_CLASSES_TIME,
};

export const instructorTypes = {
  FETCH_INSTRUCTOR_CLASSES_START,
  FETCH_INSTRUCTOR_CLASSES_SUCCESS,
  FETCH_INSTRUCTOR_CLASSES_FAILURE,
};
export default types;
